### ISSUE TITLE
Error: unsupported version of the Socket.IO or Engine.IO

### ISSUE THREAD

**Issue by kimthostrup** [mikeabrahamsen/Flask-Meld-Example#1]
Hi, I get the following error message when running the Flask-Meld-Example
----snip----
The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
----snip----
Env. Mac 11.0.1, Chrome Version 87.0.4280.88 (Official Build) (x86_64), Python 3.8.5

**Comment by mikeabrahamsen** [comment]
Thanks for the submission!  I've made a new release to fix this. Update to the newest version of Flask-Meld and it will work as expected again.

**Comment by kimthostrup** [comment]
Perfect, now it works like a charm :-)
